[package]
name = "stun_client"
version = "0.1.0"
authors = ["Daniel Frederico Lins Leite <xunilrj@hotmail.com>"]
edition = "2018"

[dependencies]
mio = {version = "0.7.6", features = ["os-poll", "udp"]}
