set dotenv-load

build-release:
    cargo build --release

export-guybrush-skl: build-release
    target/release/tomi convert-skl \
        -p /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl \
        -o target/outputs/sk20_guybrush.gltf

export-guybrush-walk: build-release
    target/release/tomi convert-anm \
        --mesh /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
        --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl \
        --anm /mnt/d/downloads/ttarctext/a/sk20_move_guybrushwalk.anm  \
        -o viewer/models/result.gltf

export-guybrush-walkdeterminedship: build-release
    target/release/tomi convert-anm \
        --mesh /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
        --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl \
        --anm /mnt/d/downloads/ttarctext/a/sk20_move_guybrushwalkdeterminedship.anm \
        -o viewer/models/result.gltf

default: export-guybrush-skl