set dotenv-load

build-release:
    cargo build --release

export-guybrush-skl: build-release
    target/release/tomi convert-skl \
        -p /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl \
        -o target/outputs/sk20_guybrush.gltf

export-guybrush-walk: build-release
    target/release/tomi convert-anm \
        -p /mnt/d/downloads/ttarctext/a/sk20_move_guybrushwalk.anm  \
        --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl \
        -o viewer/models/result.gltf

export-guybrush-idle: build-release
    target/release/tomi convert-anm \
        -p /mnt/d/downloads/ttarctext/a/sk20_idle_guybrush.anm  \
        --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl \
        -o viewer/models/result.gltf

export-guybrush-idle-chore: build-release
    target/release/tomi convert-chore \
        -p /mnt/d/downloads/ttarctext/a/sk20_move_guybrushwalkdeterminedship.chore  \
        -o viewer/models/sk20_move_guybrushwalkdeterminedship.chore.json
    
# export-guybrush-mesh: build-release
#     target/release/telltaleconv mesh-convert \
#         -p /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
#         -o ~/myprojects/tower/assets/meshes/guybrush/guybrush.gltf \
#         --texture-path /mnt/d/downloads/ttarctext/b \
#         --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl
#     target/release/telltaleconv mesh-convert \
#         -p /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
#         -o viewer/models/result.gltf \
#         --texture-path /mnt/d/downloads/ttarctext/b \
#         --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl

# export-guybrush-idle: build-release
#     target/release/telltaleconv anm-convert \
#         -p /mnt/d/downloads/ttarctext/a/sk20_idle_guybrush.anm \
#         -o ~/myprojects/tower/assets/meshes/guybrush/idle.gltf \
#         --mesh /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
#         --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl

# export-guybrush-walk: build-release
#     target/release/telltaleconv anm-convert \
#         -p /mnt/d/downloads/ttarctext/a/sk20_move_guybrushwalk.anm \
#         -o ~/myprojects/tower/assets/meshes/guybrush/walk.gltf \
#         --mesh /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
#         --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl

# export-guybrush-pickup-low: build-release
#     target/release/telltaleconv anm-convert \
#         -p /mnt/d/downloads/ttarctext/a/sk20_guybrush_pickuplow.anm \
#         -o ~/myprojects/tower/assets/meshes/guybrush/pickup_low.gltf \
#         --mesh /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
#         --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl
#     target/release/telltaleconv anm-convert \
#         -p /mnt/d/downloads/ttarctext/a/sk20_guybrush_pickuplow.anm \
#         -o viewer/models/guybrush_pickuplow.gltf \
#         --mesh /mnt/d/downloads/ttarctext/a/sk20_guybrush.d3dmesh \
#         --skl /mnt/d/downloads/ttarctext/a/sk20_guybrush.skl
    

# export-props: build-release
#     target/release/telltaleconv mesh-convert \
#         -p /mnt/d/downloads/ttarctext/a/obj_keymonkey.d3dmesh \
#         -o ~/myprojects/tower/assets/meshes/props/obj_rootsplantchuck.gltf

# all: export-props export-guybrush-mesh export-guybrush-idle export-guybrush-walk export-guybrush-pickup-low

default: export-guybrush-skl