# Find the native T1M3BASE headers and libraries.
#
#  T1M3BASE_LIBRARIES    - List of libraries when using nana.
#  T1M3BASE_FOUND        - True if nana found.

# Look for the library.
FIND_LIBRARY(T1M3BASE_LIBRARY NAMES FOSSSimT1M3base HINTS ${CMAKE_SOURCE_DIR}/lib)
MARK_AS_ADVANCED(T1M3BASE_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set T1M3BASE_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(T1M3BASE DEFAULT_MSG T1M3BASE_LIBRARY)

IF(T1M3BASE_FOUND)
  SET(T1M3BASE_LIBRARIES ${T1M3BASE_LIBRARY})
ELSE(T1M3BASE_FOUND)
  SET(T1M3BASE_LIBRARIES)
ENDIF(T1M3BASE_FOUND)