#! /bin/bash
clang++-10 main.cpp -o main -O3 -g # -O3 -g allow kcachegrind to show profile per sourceline

echo "Test 00"
time ./main < input00.txt
#echo "Test 01"
#time ./main < input01.txt
#echo "Test 02"
#time ./main < input02.txt
#echo "Test 05"
#time ./main < input05.txt
