#! /bin/bash
clang++-10 main.cpp -o main -O3 -g -std=c++2a -I/usr/include/libdwarf -L/usr/lib/x86_64-linux-gnu -ldwarf -lelf -ldl # -O3 -g allow kcachegrind to show profile per sourceline

echo "Test 00"
time ./main < input00.txt

echo "Test 01"
time ./main < input01.txt

echo "Test 02"
time ./main < input02.txt

echo "Test 05"
time ./main < input05.txt

echo "Test 10"
time ./main < input10.txt

echo "Test 19"
time ./main < input19.txt
