# Find the native T1M2BASE headers and libraries.
#
#  T1M2BASE_LIBRARIES    - List of libraries when using nana.
#  T1M2BASE_FOUND        - True if nana found.

# Look for the library.
FIND_LIBRARY(T1M2BASE_LIBRARY NAMES FOSSSimT1M2base HINTS ${CMAKE_SOURCE_DIR}/lib)
MARK_AS_ADVANCED(T1M2BASE_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set T1M2BASE_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(T1M2BASE DEFAULT_MSG T1M2BASE_LIBRARY)

IF(T1M2BASE_FOUND)
  SET(T1M2BASE_LIBRARIES ${T1M2BASE_LIBRARY})
ELSE(T1M2BASE_FOUND)
  SET(T1M2BASE_LIBRARIES)
ENDIF(T1M2BASE_FOUND)