#! /bin/bash

mkdir .build -p
cp ../../../books/NumericalRecipesInC/src/* ./src/

clang++-10 src/roots.cpp -c -o .build/roots.o \
    -I/opt/wasi-sdk/share/wasi-sysroot/include/c++/v1 \
    -I/opt/wasi-sdk/share/wasi-sysroot/include \
    --target=wasm32 \
    -nostdlib \
    --std=c++2a \
    -flto \
    -ffunction-sections \
    -fdata-sections \
    -O3 \
    -Xclang -load -Xclang plugin/wasmPlugin.so -Xclang -add-plugin -Xclang wasm-extract-contract -Xclang -plugin-arg-wasm-extract-contract -Xclang .build/roots.json

clang++-10 src/math.cpp -c -o .build/math.o \
    -I/opt/wasi-sdk/share/wasi-sysroot/include/c++/v1 \
    -I/opt/wasi-sdk/share/wasi-sysroot/include \
    --target=wasm32 \
    -nostdlib \
    --std=c++2a \
    -flto \
    -ffunction-sections \
    -fdata-sections \
    -O3 \
    -Xclang -load -Xclang plugin/wasmPlugin.so -Xclang -add-plugin -Xclang wasm-extract-contract -Xclang -plugin-arg-wasm-extract-contract -Xclang .build/math.json

wasm-ld-10 .build/roots.o .build/math.o /opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi/crt1.o \
		-o .build/math.wasm \
		--no-entry \
		-O3 \
		-lto-O3 \
		--export-dynamic \
		--gc-sections \
		--import-memory
    
node plugin/merge.js \
    .build/math.json \
    .build/roots.json > .build/merged.json  

node plugin/generate.js \
    .build/merged.json > .build/math.js  