# Find the native T1M1BASE headers and libraries.
#
#  T1M1BASE_LIBRARIES    - List of libraries when using nana.
#  T1M1BASE_FOUND        - True if nana found.

# Look for the library.
FIND_LIBRARY(T1M1BASE_LIBRARY NAMES FOSSSimT1M1base HINTS ${CMAKE_SOURCE_DIR}/lib)
MARK_AS_ADVANCED(T1M1BASE_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set T1M1BASE_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(T1M1BASE DEFAULT_MSG T1M1BASE_LIBRARY)

IF(T1M1BASE_FOUND)
  SET(T1M1BASE_LIBRARIES ${T1M1BASE_LIBRARY})
ELSE(T1M1BASE_FOUND)
  SET(T1M1BASE_LIBRARIES)
ENDIF(T1M1BASE_FOUND)