[package]
name = "streams_rs"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
nix = "0.20.2"
bytes = "0.6.0"
notify = "4.0.15"
fs2 = "0.4.3"
criterion = "0.3"
extension-trait = "0.2.3"
chrono = "0.4.19"

[[bench]]
name = "my_benchmark"
harness = false